name = "Test-mysqld"
badges = ["travis"]
authority="cpan:KAZUHO"

module_maker="ModuleBuildTiny"
markdown_maker = "Pod::Markdown::Github"

[FileGatherer]
exclude_match = ['^xt/copy-data-from-mysql8*', '^author/*', 'minil.toml']
